# Generated by Django 5.2 on 2025-06-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('tickets', 'Отчет по заявкам'), ('support', 'Отчет по специалистам'), ('users', 'Отчет по пользователям'), ('general', 'Общий отчет')], max_length=20, verbose_name='Тип отчета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='report_system.report', verbose_name='Отчет')),
            ],
            options={
                'verbose_name': 'Данные отчета',
                'verbose_name_plural': 'Данные отчетов',
                'ordering': ['-created_at'],
            },
        ),
    ]
