# Generated by Django 5.2 on 2025-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
