# Generated by Django 5.2 on 2025-06-04 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0002_alter_ticketmessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1 звёзд'), (2, '2 звёзд'), (3, '3 звёзд'), (4, '4 звёзд'), (5, '5 звёзд')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='support_system.ticket', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Оценивший пользователь')),
            ],
            options={
                'verbose_name': 'Оценка специалиста',
                'verbose_name_plural': 'Оценки специалистов',
                'ordering': ['-created_at'],
            },
        ),
    ]
