# Generated by Django 5.2 on 2025-06-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0003_supportrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='support_system.category', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='support_system.category', verbose_name='Раздел'),
        ),
    ]
